title: elegant-autoindex
description: >-
  Stylish sortable autoindex template for nginx.

baseurl: /elegant-autoindex
domain: remino.github.io
url: https://remino.github.io

defaults:
  - scope:
      type: pages
    values:
      layout: default

exclude:
  - etc/
  - jeksite
  - var/

include:
  - .htaccess
