autoindex on;
autoindex_format xml;
set $elegant_autoindex_show_attribution "true";
xslt_stylesheet /var/lib/nginx/elegant-autoindex/transform.xslt;
xslt_string_param currentDir $uri;
xslt_string_param showAttribution $elegant_autoindex_show_attribution;
